# Generated by Django 3.2.8 on 2021-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_inputs',
            field=models.FileField(blank=True, null=True, upload_to='inputs/'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_outputs',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
    ]
