# Generated by Django 3.2.8 on 2021-10-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seer', '0002_auto_20211021_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='verdict',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('In Queue', 'In Queue'), ('Running', 'Running'), ('WA', 'WA'), ('TLE', 'TLE'), ('Accepted', 'Accepted')], default='In Queue', max_length=31),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C++', 'C++'), ('C', 'C'), ('Python', 'Python'), ('Java', 'Java')], max_length=31, null=True),
        ),
    ]
